const data = {
  users: [
    {
      name: 'Basir',
      email: 'admin@example.com',
      password: 123456,
      isAdmin: true,
    },
    {
      name: 'john',
      email: 'user@gmail.com',
      password: 123456,
      isAdmin: false,
    },
  ],
  product: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirt',
      image: '/images/p1.jpeg',
      price: 120,
      countInStock: 3,
      brand: 'Nike',
      rating: 4.5,
      numReviwes: 10,
      description: 'high quality shirt',
    },
    {
      _id: '2',
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpeg',
      price: 120,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviwes: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-Pant',
      category: 'Pants',
      image: '/images/p3.jpeg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviwes: 14,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-Pant',
      category: 'Pants',
      image: '/images/p4.jpeg',
      price: 120,
      countInStock: 10,
      brand: 'adidas',
      rating: 4.5,
      numReviwes: 14,
      description: 'high quality product',
    },
  ],
};
export default data;
